// <auto-generated />
using Kabus.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kabus.Api.Migrations
{
    [DbContext(typeof(KabusDb))]
    partial class KabusDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Kabus.Api.Database.DbTopic", b =>
                {
                    b.Property<string>("Uid")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Uid");

                    b.ToTable("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
